name: tensorrl

dependencies:
  - python=3.6
  - ipython
  - jupyter
  - matplotlib
  - scikit-learn
  - opencv
  - pip:
    - tf-nightly-2.0-preview
    - dicto
    - tqdm
    - keras-rl
    - fire
    - gym
    - scipy