memory_limit: 50000
target_model_update: 0.01
gamma: 0.99
warmup_steps: 1024
batch_size: 256
summary_steps: 100
save_steps: 10000
max_steps: 1000000
learning_rate: 0.001
seed: 123
# regularization: 0.0001
eval_episode_frequency: 20
eval_episodes: 2